BASE <http://team-zolw/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?krol
WHERE {
  <#walka-o-wladze> <#wojna-pieciu-krolow> [
      a rdf:Seq ;
      rdfs:member ?krol
  ]
}
LIMIT 10
